CREATE TABLE ORDERS1(
    ID NUMBER CHECK(ID <= 10000),
    CONSTRAINT ID_PK PRIMARY KEY (ID),
    USER_ID NUMBER UNIQUE,
    ROOM_ID NUMBER UNIQUE,
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID NUMBER(*,2)
);