CREATE TABLE ORDER_DETAILS(
    OrderID NUMBER,
    CONSTRAINT OrderID_FK FOREIGN KEY (OrderID) REFERENCES ORDERS (OrderID),
    ProductID NUMBER,
    CONSTRAINT ProductID_FK FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID),
    UnitPrice NUMBER,
    Quantity NUMBER,
    Discount NUMBER
);