CREATE TABLE MOVIE(
ID NUMBER,
CONSTRAINT ID_PRIMKEY PRIMARY KEY (ID),
TITLE VARCHAR2(50) UNIQUE NOT NULL,
DIRECTOR VARCHAR2(50) UNIQUE NOT NULL,
YEAR NUMBER(4) CHECK (YEAR BETWEEN 1900 AND 2018),
LENGTH_MINS NUMBER CHECK (LENGTH_MINS BETWEEN 10 AND 200)
);